### ISSUE TITLE
Project Status/Documentation

### ISSUE THREAD

**Issue by gsingh93** [sivadeilra/racc#2]
What is the current status of this project? I see it on crates.io, but there's no documentation or examples so I don't know how to use it.

**Comment by geraldstanje** [comment]
hi, could you please report the status?

**Comment by kirbyfan64** [comment]
@sivadeilra Hello?

**Comment by kirbyfan64** [comment]
Turns out there's some nice documentation as comments in [lib.rs](https://github.com/sivadeilra/racc/blob/master/src/lib.rs).

**Comment by gsingh93** [comment]
I doubt this builds though. In any case, I've been happy using rust-peg.

**Comment by sivadeilra** [comment]
Hi, Ryan.  I haven't done any work on RACC in months.  I'm sure it no
longer builds.

If you are interested in using RACC, I could probably spend a few hours
getting it working again.

**Comment by kirbyfan64** [comment]
@sivadeilra I'm definitely considering using Rust+RACC for a compiler project I'm working on. Right now, I wrote it in [Hy](http://docs.hylang.org/en/latest/) (a Lisp frontend for Python), but it's kind of slow and slightly tricky to debug. Coming a C++ world, I've found Rust very interesting.

For one thing, I like YACC-like tools, and right know the only two I know of that aren't absolute utter crap are this and Python's PLY.

**Comment by sivadeilra** [comment]
Well, I'll grab the latest rustc, and see whether I can get racc working
again.  Either way, I'll let you know.

**Comment by kirbyfan64** [comment]
@sivadeilra Well, Rust just hit 1.0, and they're committed to stop making major breaking changes often, so I doubt you would really have to try to continue keeping up with the newest Rust version anymore.

**Comment by geraldstanje** [comment]
@sivadeilra seems like you update your source to compile with rust 1.0? thanks for the effort.

**Comment by sivadeilra** [comment]
Oh, sure.  But I don't deserve the credit -- that PR was contributed by
Brandon Chinn.

**Comment by gsingh93** [comment]
If this is working now, you can close this issue and update the readme to say the project is functional.
